import IMP.pynet

deadline_ms: int

class TestAIS(IMP.test.TestCase):
    rtol: float
    atol: float
    def test_sample_trivial(self, n_samples, n_inter) -> None: ...
    def test_specialized_model_to_sampling_trivial(decimal: int): ...
    def test_nsteps_mh__g(self, mu, sigma) -> None: ...
    def test_nsteps_mh__g_accuracy(self) -> None: ...
    def test_apply_normal_context_to_sample(self) -> None: ...
    def test_f0_pdf__j(self) -> None: ...
    def test_fn_pdf__j(self) -> None: ...
    def test_fj_pdf__g(self) -> None: ...
    def test_T_nsteps__unorm2unorm__p(self) -> None: ...
    def test_T_nsteps_mh__g(self) -> None: ...
    def test_do_ais(self) -> None: ...
