import IMP.pynet
from .source import example as example
from hypothesis import settings as settings

class PropertyTests(IMP.test.TestCase):
    def test_a_lt_b(self, a, b) -> None: ...
    def test_a_lt_b2(self, a, b) -> None: ...
    def test_a_lt_b3(self, a, b) -> None: ...
