import IMP.algebra
from functools import partial as partial
from jax import jit as jit, lax as lax, pmap as pmap, vmap as vmap
from jax.experimental.maps import mesh as mesh
from typing import Any

class ArrayType:
    def __getitem__(self, idx): ...

f32: Any
i32: Any

class TestXMAP(IMP.test.TestCase):
    def test_unary_functions(self): ...

class TestSparse(IMP.test.TestCase):
    atol: float
    rtol: float
    def test_matmul(self) -> None: ...
    def test_add(self) -> None: ...
    def test_subtract(self) -> None: ...
    def test_multiply(self) -> None: ...
    def test_log(self) -> None: ...
    def test_sparse_jit(self): ...

class TestPMAP(IMP.test.TestCase): ...
