import IMP.pynet
from typing import Any

def get_test_path(): ...

class TestMyGene(IMP.test.TestCase): ...

class TestPoissonSQR(IMP.test.TestCase):
    seed0: int
    key0: Any
    p0: int
    phi0: Any
    theta: Any
    phi: Any
    X: Any
    p: Any
    n: Any
    def test__get_vec_minus_s(self) -> None: ...
    def test_matrix_minus_slice(self): ...
    def test_eta1_eta2_jittable(self) -> None: ...
    def test_Aexp_evaluation(self) -> None: ...
    def test_ll_exponential_sqr(self) -> None: ...
    def test_log_exponential_sqr(self) -> None: ...

class TestBiogridDataLoading(IMP.test.TestCase):
    def test_ncbi_gene_id(self) -> None: ...

class TestSpectralCountsDataLoading(IMP.test.TestCase): ...
