import IMP.algebra
from typing import Any

class TestGraph(IMP.test.TestCase):
    module: Any
    def test_print(self) -> None: ...
    def test_nnodes(self) -> None: ...
    def test_equal(self) -> None: ...
    def test_neg(self) -> None: ...
    def test_class_names(self) -> None: ...
    def test_function_names(self) -> None: ...
