import IMP.algebra

class TestII(IMP.test.TestCase):
    def test_get_dataset_overlap(self) -> None: ...
    def test_neg(self) -> None: ...
    def test_neg2(self) -> None: ...
    def test_fail3(self) -> None: ...
    def test_pass(self) -> None: ...
