import IMP.pynet

deadline_ms: int

class MediumTestAIS(IMP.test.TestCase):
    rtol: float
    atol: float
    trivial_n_samples: int
    trvial_n_inter: int
    def test_sample_trivial(self) -> None: ...
    def test_sample_trivial2(self) -> None: ...
    def test_sample_trivial3(self) -> None: ...
    def test_sample_trivial4(self) -> None: ...
    def test_sample_trivial5(self) -> None: ...
    def test_sample_trivial6(self) -> None: ...
    def test_sample_trivial7(self) -> None: ...
    def test_sample_trivial7(self) -> None: ...
    def test_not_ones_trivial(self) -> None: ...
    def test_nsteps_mh__g(self, mu, sigma) -> None: ...
