import IMP.algebra
from hypothesis import settings as settings

class NegativeTestAIS(IMP.test.TestCase):
    def test_negative_sample_trivialI(self, seed1: int, seed2: int): ...
    def test_negative_sample_trivial2(self, n_samples) -> None: ...
