PRINT_ON: bool

def printf(s) -> None: ...

class TestSampling(IMP.test.TestCase):
    def test_degree_prior(self) -> None: ...
    def test_e_base(self) -> None: ...
    def test_edge_id(self) -> None: ...
    def test_plot_dataset_overlap(self) -> None: ...
    def run_tests(self) -> None: ...
    def test_fail(self) -> None: ...
    def test_fail2(self) -> None: ...
    def test_fail3(self) -> None: ...
