import IMP.pynet
from typing import Any

class Tests(IMP.test.TestCase):
    module: Any
    def test_magnitude(self) -> None: ...
    def test_function_names(self) -> None: ...
    def test_class_names(self) -> None: ...
