from typedefs import Function as Function, Parameters as Parameters
from typing import Any

def parameters(f: Function): ...
def Domain(f: Function) -> Parameters: ...
def Codomain(f: Function): ...
def composable(f: Function) -> set[Function]: ...

y: Any
