from scipy.stats import f_oneway as f_oneway
from typing import Any

src: Any

def read_lip_data(): ...
def format_lip_data(df): ...
def summarize_lip_data(): ...
def summarize_gordon_data(): ...
def read_stuk_apms_data() -> None: ...
def read_gordon_data() -> None: ...
def summarize_stuk_data(): ...
def overlap(a, b): ...
def get_dataset_overlap(dataset_dict, dataset_names: Any | None = ...): ...
