from pyext.src.typedefs import Array1d as Array1d

def marginal(x: Array1d, xlabel: str = ..., ylabel: str = ..., bins: int = ..., **kwargs): ...
def scatter(x: Array1d, y: Array1d, xlabel: str = ..., ylabel: str = ..., **kwargs): ...
