from typing import Any

synthetic_spec_counts_data: Any

def represent_network(n): ...
def register_restraints() -> None: ...
def poisson_sqrgm(vertex_set, data): ...
def sample(M, D, PRNGKey): ...
def plot_MCMC_chain(samples) -> None: ...
def check_R_hat(samples): ...
def KL_divergence_test(samples): ...
def plot_sample_edge_mean(samples) -> None: ...
def plot_sample_edge_variance(samples) -> None: ...
def cluster_models(samples): ...
