from pathlib import Path
from typing import Any

pynet_home: Any

def modparse(local_dict): ...
def moduleinfo(local_dict) -> None: ...
def doc(x) -> None: ...
def psrc(x) -> None: ...
def ls(p: Path): ...
