from pyext.src.typedefs import AnyPath as AnyPath, DirPath as DirPath, FilePath as FilePath

def write_excel_files(working_dir: DirPath) -> list[FilePath]: ...
def xlsx_promt(file) -> None: ...
def parse_sheets(file) -> None: ...
def export_sheet(sheet, file) -> None: ...
def get_sep(mcase: str) -> str: ...
def concat(sl: list[str]) -> str: ...
def format_filename(file, sheet, mcase): ...
