from pyext.src.score import mode as mode

def plot_density(length, mu, sig) -> None: ...
def MCMC_chain_plot(chain, y) -> None: ...
def chain_summary(ax, title, chain, tx, ty) -> None: ...
def summary_wrapper(chain, mu, sig) -> None: ...
def plot_parabola() -> None: ...
def plot_likelihood_func(mu, sig, length, width: float = ...) -> None: ...
