from typing import Any

FilePath: Any
DirPath: Any

def check_imp_dir_structure() -> None: ...
def is_h(f: FilePath) -> bool: ...
def is_cpp(f: FilePath) -> bool: ...
def is_exists(f: FilePath) -> bool: ...
def is_imp_module(wd: DirPath) -> bool: ...
def get_module_name(wd: DirPath) -> str: ...
