from collections.abc import Generator
from typing import Any

L: Any
it: Any

def my_generator(x) -> Generator[Any, Any, None]: ...
def my_gen2(x) -> Generator[Any, None, None]: ...
def my_gen3(x) -> Generator[Any, Any, None]: ...
def counter(maximum) -> Generator[Any, Any, None]: ...
